name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag home-assistant:dev
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
